### ISSUE TITLE
Failed to run on GPU

### ISSUE THREAD

**Issue by Dongfeng-He** [memray/seq2seq-keyphrase-pytorch#15]
It ran just well on CPU, however, when I was trying to run it on a Cloud GPU, it threw an error as below:

2018-12-05 02:02:01 PSTRun Output:
2018-12-05 02:02:01 PST Starting services.
2018-12-05 02:02:09 PST Traceback (most recent call last):
2018-12-05 02:02:09 PST File "train.py", line 752, in <module>
2018-12-05 02:02:09 PST main()
2018-12-05 02:02:09 PST File "train.py", line 725, in main
2018-12-05 02:02:09 PST opt = init_opt(description='train.py')
2018-12-05 02:02:09 PST File "/floyd/home/config.py", line 25, in init_opt
2018-12-05 02:02:09 PST if torch.cuda.is_available() and not opt.device_ids:
2018-12-05 02:02:09 PST AttributeError: 'Namespace' object has no attribute 'device_ids'

I tried to solve this problem by simply assigning a value to opt.device_ides. After that, it threw another error:

2018-12-05 02:16:41 PST ERROR:train.py:Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'
2018-12-05 02:16:41 PST Traceback (most recent call last):
2018-12-05 02:16:41 PST File "train.py", line 745, in main
2018-12-05 02:16:41 PST train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loader, test_data_loader, opt)
2018-12-05 02:16:41 PST File "train.py", line 467, in train_model
2018-12-05 02:16:41 PST loss_ml, decoder_log_probs = train_ml(one2one_batch, model, optimizer_ml, criterion, opt)
2018-12-05 02:16:41 PST File "train.py", line 113, in train_ml
2018-12-05 02:16:41 PST decoder_log_probs, _, _ = model.forward(src, src_len, trg, src_oov, oov_lists)
2018-12-05 02:16:41 PST File "/floyd/home/pykp/model.py", line 402, in forward
2018-12-05 02:16:41 PST src_h, (src_h_t, src_c_t) = self.encode(input_src, input_src_len)
2018-12-05 02:16:41 PST File "/floyd/home/pykp/model.py", line 416, in encode
2018-12-05 02:16:41 PST src_emb = self.embedding(input_src)
2018-12-05 02:16:41 PST File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
2018-12-05 02:16:41 PST result = self.forward(*input, **kwargs)
2018-12-05 02:16:41 PST File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 110, in forward
2018-12-05 02:16:41 PST self.norm_type, self.scale_grad_by_freq, self.sparse)
2018-12-05 02:16:41 PST File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 1110, in embedding
2018-12-05 02:16:41 PST return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
2018-12-05 02:16:41 PST RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'
2018-12-05 02:16:41 PST Traceback (most recent call last):
2018-12-05 02:16:41 PST File "train.py", line 752, in <module>
2018-12-05 02:16:41 PST main()
2018-12-05 02:16:41 PST File "train.py", line 745, in main
2018-12-05 02:16:41 PST train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loader, test_data_loader, opt)
2018-12-05 02:16:41 PST File "train.py", line 467, in train_model
2018-12-05 02:16:41 PST loss_ml, decoder_log_probs = train_ml(one2one_batch, model, optimizer_ml, criterion, opt)
2018-12-05 02:16:41 PST File "train.py", line 113, in train_ml
2018-12-05 02:16:41 PST decoder_log_probs, _, _ = model.forward(src, src_len, trg, src_oov, oov_lists)
2018-12-05 02:16:41 PST File "/floyd/home/pykp/model.py", line 402, in forward
2018-12-05 02:16:41 PST src_h, (src_h_t, src_c_t) = self.encode(input_src, input_src_len)
2018-12-05 02:16:41 PSTFile "/floyd/home/pykp/model.py", line 416, in encode
2018-12-05 02:16:41 PST src_emb = self.embedding(input_src)
2018-12-05 02:16:41 PST File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
2018-12-05 02:16:41 PST result = self.forward(*input, **kwargs)
2018-12-05 02:16:41 PST File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 110, in forward
2018-12-05 02:16:41 PST self.norm_type, self.scale_grad_by_freq, self.sparse)
2018-12-05 02:16:41 PST File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 1110, in embedding 
2018-12-05 02:16:41 PST return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
2018-12-05 02:16:41 PST RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'

It seems that some parts of the model were built to run on CPU and other parts were for GPU?
Look forward to your reply

**Comment by memray** [comment]
Hi Dongfeng,

Please check out the latest version. I corrected some bugs related to gpu setting. Let me know if you run into new problems.

Rui

**Comment by Dongfeng-He** [comment]
Hi Rui,

Thank you very much! No more runtime error when training on GPU
Thanks again for your great job

**Comment by pidugusundeep** [comment]
How much time did it take you to run on the GPU? @Dongfeng-He, Is there any chance you could provide me the model file?
