### ISSUE TITLE
RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'

### ISSUE THREAD

**Issue by loveJasmine** [memray/seq2seq-keyphrase-pytorch#17]
INFO:root:Training Epoch=11 - 43/195 (22.05%)[.....(-w-)~~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 2s - ETA: 9s
INFO:root:Training Epoch=11 - 44/195 (22.56%)[.....(-w-)~~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 2s - ETA: 9s
INFO:root:Training Epoch=11 - 45/195 (23.08%)[.....(-w-)~~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 2s - ETA: 9s
INFO:root:Training Epoch=11 - 46/195 (23.59%)[......(-w-)~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 2s - ETA: 9s
INFO:root:Training Epoch=11 - 47/195 (24.10%)[......(-w-)~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 3s - ETA: 9s
INFO:root:Training Epoch=11 - 48/195 (24.62%)[......(-w-)~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 3s - ETA: 9s
INFO:root:Training Epoch=11 - 49/195 (25.13%)[......(-w-)~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 3s - ETA: 9s
INFO:root:Training Epoch=11 - 50/195 (25.64%)[......(-w-)~~~~~~~~~~~~~~~~~~~~~~~] - Run-time: 3s - ETA: 9s
INFO:root:**************************************************
INFO:root:Run validing and testing @Epoch=11,#(Total batch)=2000
INFO:Validating, epoch=11, batch=50, total_batch=2000:Initializing logger: Validating, epoch=11, batch=50, total_batch=2000
INFO:Validating, epoch=11, batch=50, total_batch=2000:Making log output file: exp/kp20k.20181214-114656/pred//epoch11_batch50_total_batch2000/Validating, epoch=11, batch=50, total_batch=2000.log
INFO:Validating, epoch=11, batch=50, total_batch=2000:exp/kp20k.20181214-114656/pred//epoch11_batch50_total_batch2000
batch size - 1
src size - torch.Size([1, 166])
target size - 1
ERROR:train.py:Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'
Traceback (most recent call last):
  File "train.py", line 746, in main
    train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loader, test_data_loader, opt)
  File "train.py", line 494, in train_model
    valid_score_dict = evaluate_beam_search(generator, valid_data_loader, opt, title='Validating, epoch=%d, batch=%d, total_batch=%d' % (epoch, batch_i, total_batch), epoch=epoch, predict_save_path=opt.pred_path + '/epoch%d_batch%d_total_batch%d' % (epoch, batch_i, total_batch))
  File "/home/gpuws/ub16_prj/seq2seq-keyphrase-pytorch/evaluate.py", line 185, in evaluate_beam_search
    pred_seq_list = generator.beam_search(src_list, src_len, src_oov_map_list, oov_list, opt.word2id)
  File "/home/gpuws/ub16_prj/seq2seq-keyphrase-pytorch/beam_search.py", line 219, in beam_search
    src_context, (src_h, src_c) = self.model.encode(src_input, src_len)
  File "/home/gpuws/ub16_prj/seq2seq-keyphrase-pytorch/pykp/model.py", line 416, in encode
    src_emb = self.embedding(input_src)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/sparse.py", line 108, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1076, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'
Traceback (most recent call last):
  File "train.py", line 753, in <module>
    main()
  File "train.py", line 746, in main
    train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loader, test_data_loader, opt)
  File "train.py", line 494, in train_model
    valid_score_dict = evaluate_beam_search(generator, valid_data_loader, opt, title='Validating, epoch=%d, batch=%d, total_batch=%d' % (epoch, batch_i, total_batch), epoch=epoch, predict_save_path=opt.pred_path + '/epoch%d_batch%d_total_batch%d' % (epoch, batch_i, total_batch))
  File "/home/gpuws/ub16_prj/seq2seq-keyphrase-pytorch/evaluate.py", line 185, in evaluate_beam_search
    pred_seq_list = generator.beam_search(src_list, src_len, src_oov_map_list, oov_list, opt.word2id)
  File "/home/gpuws/ub16_prj/seq2seq-keyphrase-pytorch/beam_search.py", line 219, in beam_search
    src_context, (src_h, src_c) = self.model.encode(src_input, src_len)
  File "/home/gpuws/ub16_prj/seq2seq-keyphrase-pytorch/pykp/model.py", line 416, in encode
    src_emb = self.embedding(input_src)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/sparse.py", line 108, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1076, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'
gpuws@gpuws32g:~/ub16_prj/seq2seq-keyphrase-pytorch$

**Comment by memray** [comment]
I didn't test the predict part on GPU quite much. I guess something is not properly put to GPU. Run it in debug mode and check which variables are not CudaTensor, and convert it with [cuda()](https://pytorch.org/docs/stable/notes/cuda.html).
